// templates/farm/vue-lite/src/App.vue
<template>
  <t-space direction="vertical" style="width: 100%; text-align: center">
    <t-space>
      <a href="https://tdesign.tencent.com/vue/overview" target="_blank">
        <img src="../public/tdesign-logo.svg" class="logo tdesign" alt="TDesign" />
      </a>
      <a href="https://www.farmfe.org/" target="_blank">
        <img src="./assets/svg/farm-logo.png" class="logo farm" alt="Farm" />
      </a>
    </t-space>
    <h2> Welcome to use
      <t-link size="large" theme="primary" href="https://tdesign.tencent.com/vue/overview" target="_blank">
        <jump-icon slot="suffixIcon" />
        TDesign-vue
      </t-link>
      +
      <t-link size="large" theme="primary" href="https://www.farmfe.org/" target="_blank">
        <jump-icon slot="suffixIcon" />
        Farm
      </t-link>
      ！
    </h2>
    <h3>
      Experience it quickly using the
      <t-link theme="warning" href="https://tdesign.tencent.com/starter/vue/" target="_blank">
        <jump-icon slot="suffixIcon" />
        TDesign Starter
      </t-link>
      page template.
    </h3>

    <t-space>
      <t-button theme="primary">
        <add-icon slot="icon" />
        新建
      </t-button>
      <t-button variant="outline">
        <cloud-upload-icon slot="icon" />
        上传文件
      </t-button>
      <t-button shape="circle" theme="primary">
        <discount-icon slot="icon" />
      </t-button>
      <t-button shape="circle" theme="primary">
        <cloud-download-icon slot="icon" />
      </t-button>
      <t-button variant="outline"> 搜索 </t-button>
    </t-space>
  </t-space>
</template>

<script>
import Vue from "vue";
import {
  AddIcon,
  CloudUploadIcon,
  DiscountIcon,
  CloudDownloadIcon,
  JumpIcon
} from "tdesign-icons-vue";

export default Vue.extend({
  components: {
    AddIcon,
    CloudUploadIcon,
    DiscountIcon,
    CloudDownloadIcon,
    JumpIcon
  },
});
</script>

<style>
.logo {
  height: 6em;
  padding: 3em 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo.tdesign:hover {
  filter: drop-shadow(0 0 2em #194de9);
}

.logo.farm:hover {
  filter: drop-shadow(0 0 2em #bd34fe);
}

</style>

// templates/farm/react-lite/src/App.tsx
import * as React from "react"
import { Button, ConfigProvider, Link, Space } from 'tdesign-react';
import { AddIcon, CloudUploadIcon, DiscountIcon, CloudDownloadIcon, JumpIcon } from 'tdesign-icons-react';
import TDesignLogo from '../public/tdesign-logo.svg';
import FarmLogo from './assets/svg/farm-logo.png';
import './App.css';

const App: React.FC = () => {
  return (
    <ConfigProvider globalConfig={{ classPrefix: 't' }}>
      <Space direction='vertical' style={{ width: '100%', textAlign: 'center' }}>
        <Space>
          <a href="https://tdesign.tencent.com/react/overview" target="_blank">
            <img src={TDesignLogo} className="logo tdesign" alt="TDesign" />
          </a>
          <a href="https://www.farmfe.org/" target="_blank">
            <img src={FarmLogo} className="logo farm" alt="Farm" />
          </a>
        </Space>
        <h2> Welcome to use
          <Link size="large" theme="primary" href="https://tdesign.tencent.com/react/overview" suffixIcon={<JumpIcon />} target="_blank">
            TDesign-react
          </Link>
          +
          <Link size="large" theme="primary" href="https://www.farmfe.org/" suffixIcon={<JumpIcon />} target="_blank">
            Farm
          </Link>
          !
        </h2>
        <h3>
          Experience it quickly using the
          <Link theme="warning" href="https://tdesign.tencent.com/starter/react/" suffixIcon={<JumpIcon />} target="_blank">
            TDesign Starter
          </Link>
          page template.
        </h3>

        <Space>
          <Button theme='primary' icon={<AddIcon />}>
            新建
          </Button>
          <Button variant='outline' icon={<CloudUploadIcon />}>
            上传文件
          </Button>
          <Button shape='circle' theme='primary' icon={<DiscountIcon />}></Button>
          <Button shape='circle' theme='primary' icon={<CloudDownloadIcon />}></Button>
          <Button variant='outline'> 搜索 </Button>
        </Space>
      </Space>
    </ConfigProvider>
  )
}
export default App
